---
- name: Check if override path is defined for customize_filesystem
  set_fact:
    custom_path: "{{ customize_node_filesystems | default( role_path + '/files/customize_filesystem' ) }}"

- name: Verify if {{ custom_path }}/master/worker is empty
  find:
    paths: "{{ custom_path }}/{{ item }}"
    recurse: yes
    follow: yes
  register: filesFound
  with_items:
    - "master"
    - "worker"
  delegate_to: localhost
  tags: customfs

- name: Modify Ignition Configs
  block:

  - name: Create OpenShift Ignition Configs
    shell: |
      /usr/local/bin/openshift-baremetal-install --dir {{ dir }} create ignition-configs

  - name: Copy Ignition Config Files
    copy:
      src: "{{ dir }}/{{ item }}.ign"
      dest: "{{ dir }}/{{ item }}.ign.orig"
      remote_src: yes
    with_items:
      - "master"
      - "worker"

  - name: Copy customize_filesystem to tempdir
    copy:
      src: "{{ custom_path }}"
      dest: "{{ tempdir }}"
      force: yes

  - name: Cleanup Any .gitkeep Files in the Fake Root
    file:
      path: "{{ tempdir }}/customize_filesystem/{{ item }}/.gitkeep"
      state: absent
      follow: yes
    with_items:
      - "master"
      - "worker"
    become: true

  - name: Augment Ignition Config Files
    script: |
      filetranspile-1.1.1.py -i {{ dir }}/{{ item }}.ign.orig -f {{ tempdir }}/customize_filesystem/{{ item }} -o {{ dir }}/{{ item }}.ign
    args:
      executable: python3
    with_items:
      - "master"
      - "worker"
    become: true

  - name: Add bond.service to the ignition config
    shell: |
      sed -i -z 's|"systemd": {}|"systemd": {"units": [{"name": "bond.service","enabled": true,"contents": "[Unit]\\nDescription=Configure BOND\\nAfter=ignition-firstboot-complete.service\\nBefore=nodeip-configuration.service kubelet.service\\n\\n[Service]\\nType=oneshot\\nExecStart=/bin/sh /usr/local/bin/create-ifcfg-files.sh\\n\\n[Install]\\nWantedBy=multi-user.target"}]}|g' {{ dir }}/{{ item }}.ign
    with_items:
      - "master"
      - "worker"
    when: create_bond_service is defined and create_bond_service == "true"

  - name: Create backup of ignition config files
    copy:
      src: "{{ dir }}/{{ item }}.ign"
      dest: "{{ dir }}/{{ item }}.ign.bkup"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0644'
      remote_src: yes
    with_items:
      - "master"
      - "worker"

  when: (filesFound | json_query('results[*].matched') | sum) > 0
  tags: customfs
